spring:
  security:
    oauth2:
      client:
        registration: #springBoot에 대한 설정
          kakao:
            client-id: ${KAKAO_CLIENT_ID}     # Rest Api 키
            client-secret: ${KAKAO_CLIENT_SECRET}    # 클라이언트 시크릿
            client-authentication-method: client_secret_post  # 보안 설정(클라이언트id와 시크릿을 요청본문에 포함)
            authorization-grant-type: authorization_code      # 권한 부여(인증 후 인증코드로 엑세스 토큰 요청)
            # {baseUrl}: 서버가 실행중인 프로토콜, 호스트, 포트번호를 자동으로 찾아서 주소형태로 결합
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"   #로그인 후 사용할 url 주소
            client-name: Kakao  #화면표시용
          naver:
            client-id: ${NAVER_CLIENT_ID}       # Rest Api 키
            client-secret: ${NAVER_CLIENT_SECRET}    # 클라이언트 시크릿
            client-authentication-method: client_secret_post  # 보안 설정(클라이언트id와 시크릿을 요청본문에 포함)
            authorization-grant-type: authorization_code      # 권한 부여(인증 후 인증코드로 엑세스 토큰 요청)
            # {baseUrl}: 서버가 실행중인 프로토콜, 호스트, 포트번호를 자동으로 찾아서 주소형태로 결합
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"   #로그인 후 사용할 url 주소
            client-name: NAVER  #화면표시용

        provider: # OAuth2 인증 제공자에 대한 기본 설정
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
