name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1ï¸âƒ£ ì½”ë“œ ê°€ì ¸ì˜¤ê¸°
      - name: GitHub ë¦¬í¬ì§€í† ë¦¬ì—ì„œ ìµœì‹  ì½”ë“œ ê°€ì ¸ì˜¤ê¸°
        uses: actions/checkout@v4

      # 2ï¸âƒ£ JDK 17 ì„¤ì¹˜
      - name: JDK 17 ì„¤ì¹˜
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3ï¸âƒ£ secrets ê¸°ë°˜ application.yml ìƒì„±
      - name: secrets ê¸°ë°˜ application.yml ìƒì„±
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml
          ls -l ./src/main/resources   # íŒŒì¼ í™•ì¸ìš© (ì˜µì…˜)

      # 4ï¸âƒ£ Gradle ë¹Œë“œ

      - name: Gradle ì‹¤í–‰ ê¶Œí•œ ë¶€ì—¬
        run: chmod +x ./gradlew

      - name: í…ŒìŠ¤íŠ¸ ë° ë¹Œë“œ
        run: ./gradlew clean build -x test

      # 5ï¸âƒ£ AWS ì¸ì¦
      - name: AWS ì¸ì¦ ì •ë³´ ì„¤ì •
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 6ï¸âƒ£ ECR ë¡œê·¸ì¸
      - name: AWS ECR ë¡œê·¸ì¸
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 7ï¸âƒ£ Docker ì´ë¯¸ì§€ ìƒì„±
      - name: Docker ì´ë¯¸ì§€ ìƒì„±
        run: docker build -t market-server:${{ github.sha }}

      # 8ï¸âƒ£ Docker ì´ë¯¸ì§€ íƒœê·¸
      - name: Docker ì´ë¯¸ì§€ íƒœê·¸
        run: docker tag market-server:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/market-server:${{ github.sha }}

      # 9ï¸âƒ£ Docker ì´ë¯¸ì§€ ECRì— push
      - name: Docker ì´ë¯¸ì§€ ECRì— push
        run: docker push ${{ steps.login-ecr.outputs.registry }}/market-server:${{ github.sha }}

      # ğŸ”Ÿ EC2ì—ì„œ ê¸°ì¡´ ì»¨í…Œì´ë„ˆ ì œê±° & ìƒˆ ì»¨í…Œì´ë„ˆ ì‹¤í–‰
      - name: EC2 ì ‘ì† í›„ Green Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            VERSION=${{ github.sha }}
            
            # EC2ì—ì„œ ECR ë¡œê·¸ì¸ ì¶”ê°€
            aws ecr get-login-password --region ap-northeast-2 \
            | docker login --username AWS --password-stdin 992382458231.dkr.ecr.ap-northeast-2.amazonaws.com/market-server
            
            docker stop market-server || true
            docker rm market-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/market-server:$VERSION
            docker run -d --name market-server -p 8082:8080 ${{ steps.login-ecr.outputs.registry }}/market-server:$VERSION