name: CodeDeploy Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: secrets 기반 application.yml 생성
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml
          ls -l ./src/main/resources
      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드
        run: ./gradlew clean build -x test

      - name: AWS 인증
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Docker 이미지 빌드
        run: docker build -t market-server:${{ github.sha }}

      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker 이미지 생성
        run: docker build -t market-server:${{ github.sha }}

      - name: Docker 태그 & 푸시
        run: |
          # SHA 태그
          docker tag market-server:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/market-server:${{ github.sha }}
          # latest 태그
          docker tag market-server:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/market-server:latest
          
          # ECR에 푸시
          docker push ${{ steps.login-ecr.outputs.registry }}/market-server:${{ github.sha }}
          docker push ${{ steps.login-ecr.outputs.registry }}/market-server:latest

      - name: 배포 파일 압축
        run: zip -r deploy.zip . -x ".git/*"

      - name: S3 업로드
        run: aws s3 cp deploy.zip s3://market-uploaded-files/deploy.zip


      - name: CodeDeploy 실행
        run: |
          aws deploy create-deployment \
            --application-name market-server \
            --deployment-group-name production \
            --s3-location bucket=market-uploaded-files,bundleType=zip,key=deploy.zip